### ISSUE TITLE
標籤底色

### ISSUE THREAD

**Issue by shulusama** [g0v/hacktabl#5]
標籤底色太淺了，上面的字有點難閱讀，希望可以調深一點～
![2015-12-29 5 42 12](https://cloud.githubusercontent.com/assets/7334450/12032464/95d92bf4-ae53-11e5-83c1-b534c9b91936.png)

**Comment by MrOrz** [comment]
好唷，謝謝子龍～

是說因為 label 字比較小，看起來糊在一塊，所以我也把間距稍微調大了。

**Comment by shulusama** [comment]
喔喔喔現在看起來超棒的！！+++++
